apiVersion: v1
kind: Service
metadata:
    name: "aksdror-2354"
    labels:
        app: "aksdror-2354"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksdror-2354"